name: remote-android
on: [workflow_dispatch]

jobs:
  run-android:
    runs-on: ubuntu-latest
    steps:
      - name: запуск android 13 (redroid)
        run: |
          sudo apt-get update
          # запускаем контейнер с андроидом
          docker run -itd --rm --privileged \
            --pull always \
            -p 8080:8080 \
            redroid/redroid:13.0.0-latest \
            androidboot.redroid_width=720 \
            androidboot.redroid_height=1280 \
            androidboot.redroid_dpi=320

      - name: запуск бесплатного туннеля ngrok
        run: |
          # установка ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          
          # авторизация по твоему секретному токену
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          
          # запускаем туннель в фоне
          nohup ngrok http 8080 > /dev/null 2>&1 &
          
          # ждем немного, чтобы туннель поднялся
          sleep 5
          
          # выводим твою ссылку в консоль гитхаба (в логи)
          echo "твоя ссылка для входа ниже:"
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: держать сервер включенным
        run: sleep infinity
